In [1]:
import numpy as np

In [6]:
a = np.array([[1., 4.,], [2., 5.,], [3., 6.,]])

In [8]:
a.T

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [9]:
a = np.array([[1.],[3.],[4.]])

In [10]:
a.T

array([[ 1.,  3.,  4.]])

In [18]:
a3 = np.array([[1., 4.], [3., 5.], [2., 0.]])
a4 = np.array([[2., 0.], [0., 2.]])

In [22]:
a3.dot(a4)

array([[  2.,   8.],
       [  6.,  10.],
       [  4.,   0.]])

In [23]:
a4.dot(a3)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [47]:
a5 = np.array([[1.], [2.], [3.]])

In [52]:
a6 = np.array([[2.], [4.], [6.]])

In [53]:
a5

array([[ 1.],
       [ 2.],
       [ 3.]])

In [54]:
a5.T

array([[ 1.,  2.,  3.]])

In [55]:
a6

array([[ 2.],
       [ 4.],
       [ 6.]])

In [56]:
a6.T

array([[ 2.,  4.,  6.]])

In [59]:
a5.T * a6

array([[  2.,   4.,   6.],
       [  4.,   8.,  12.],
       [  6.,  12.,  18.]])

In [58]:
a6.T * a5

array([[  2.,   4.,   6.],
       [  4.,   8.,  12.],
       [  6.,  12.,  18.]])

In [33]:
a7 = np.array([[1000., 30., 0], [1092., 49., 9.], [2064., 27., 2.]])

In [34]:
a8 = np.array([[1., 0, 0], [0, 1., 0], [0, 0, 1.]])

In [35]:
a7.dot(a8)

array([[  1.00000000e+03,   3.00000000e+01,   0.00000000e+00],
       [  1.09200000e+03,   4.90000000e+01,   9.00000000e+00],
       [  2.06400000e+03,   2.70000000e+01,   2.00000000e+00]])

In [36]:
a8.dot(a7)

array([[  1.00000000e+03,   3.00000000e+01,   0.00000000e+00],
       [  1.09200000e+03,   4.90000000e+01,   9.00000000e+00],
       [  2.06400000e+03,   2.70000000e+01,   2.00000000e+00]])