In [1]:
import numpy as np

In [6]:
x1 = np.array([2.,4.,8.])

In [8]:
x2 = np.array([0.,0.,1])

In [9]:
3 * x1 + 4 * x2

array([  6.,  12.,  28.])

In [13]:
x1 = np.array([2.0, 0.0, 3.2])

In [14]:
x2 = np.array([7.0, 5.3, 4.2])

In [15]:
4.5 * x1 - 0.1 * x2

array([  8.3 ,  -0.53,  13.98])

In [22]:
def squared(n):
    return np.power(np.arange(0,n,1),2)

def half(n):
    return np.arange(0, n, 1) / 2

x1 = squared(3)
x2 = half(3)

In [23]:
x1

array([0, 1, 4])

In [24]:
x2

array([ 0. ,  0.5,  1. ])

In [25]:
x1 + x2

array([ 0. ,  1.5,  5. ])