In [2]:
import numpy as np

In [ ]:
x1 = np.array([1.,2.,3.])

In [4]:
x2 = np.array([[1.,2.],[3.,4.]])

In [6]:
x3 = np.random.rand(3,3,3)

In [9]:
x1

array([ 1.,  2.,  3.])

In [10]:
x2

array([[ 1.,  2.],
       [ 3.,  4.]])

In [11]:
x3

array([[[ 0.31663491,  0.40565936,  0.80924681],
        [ 0.92413267,  0.12485349,  0.38396318],
        [ 0.63706602,  0.47113766,  0.14829006]],

       [[ 0.9784066 ,  0.24093534,  0.44043862],
        [ 0.92771653,  0.47949272,  0.67856963],
        [ 0.06906963,  0.38947803,  0.70728574]],

       [[ 0.12657591,  0.80870605,  0.26647114],
        [ 0.27602747,  0.79539962,  0.87122413],
        [ 0.23682943,  0.5885124 ,  0.42224396]]])

In [12]:
x1 = np.array([1,2,3])

In [13]:
x2 = np.array([4,5,6])

In [14]:
x3 = x1 + x2

In [15]:
x3

array([5, 7, 9])

In [16]:
x4 = np.array([[1,2,3], [5,1,2]])

In [17]:
x5 = np.array([[4,5,6],[10,2,0]])

In [18]:
x6 = x4 + x5

In [19]:
x6

array([[ 5,  7,  9],
       [15,  3,  2]])