In [4]:
import numpy as np
### 行列
# 演習問題1
A1 = np.array([[1, 4],
               [2, 5],
               [3, 6]])

# 転置のみ
A1.T

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 問題2
A2 = np.array([[1],
               [3],
               [4]])

# 転置のみ
print("A2.T：", A2.T)

A2.T： [[1 3 4]]


In [10]:
# 問題3
A3 = np.array([[1, 4],
               [3, 5],
               [2, 0]])

A4 = np.array([[2, 0],
               [0, 2]])

# A3*A4
print("A3*A4：", A3.dot(A4))

# A4*A3
try:
    print("A4*A3", A4.dot(A3))
except ValueError:
    print("A4*A3：解なし")

A3*A4： [[ 2  8]
 [ 6 10]
 [ 4  0]]
A4*A3：解なし


In [21]:
# 問題4
A5 = np.array([[1],
               [2],
               [3]])

A6 = np.array([[2],
               [4],
               [6]])

# 転置
tA5 = A5.T
tA6 = A6.T

# 内積
print("tA5.dot(A6)", tA5.dot(A6))
print("A5.dot(tA6)", A5.dot(tA6))

tA5.dot(A6) [[28]]
A5.dot(tA6) [[ 2  4  6]
 [ 4  8 12]
 [ 6 12 18]]


In [13]:
# 問題5
A7 = np.array([[1000, 30, 0],
               [1092, 49, 9],
               [2064, 27, 2]])

A8 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 1]])

print("A7*A8：", A7.dot(A8))

print("A8*A7：", A8.dot(A7))

A7*A8： [[1000   30    0]
 [1092   49    9]
 [2064   27    2]]
A8*A7： [[1000   30    0]
 [1092   49    9]
 [2064   27    2]]


In [ ]:
# 単位元(実数では１、行列の世界では単位行列)
I = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])


In [15]:
# 逆元(実数の世界では 指数-1乗)
A = np.array([[2, 1],
              [-1, 2]])

B = np.array([[2/5, -1/5],
              [1/5, 2/5]])

A.dot(B)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [61]:
######## レイヤーを作る ######
def set_state(x, W, b):
#     x = (w.dot(x))+1*b
#     print(x)
#     return x
    print((W.dot(x))+1*b)
    return (W.dot(x))+1*b
    
def activate(s):
    y = 1 / (1 + np.exp(-s)) 
    return y

w = np.array([[1., 2.],
              [2., 3.]])
x = np.array([[1.],
              [2.]])
b = np.array([[1.],
              [2.]])

s = set_state(x,w,b)
print("s", activate(s))


[[  6.]
 [ 10.]]
s [[ 0.99752738]
 [ 0.9999546 ]]


In [60]:
class Layer:
    
    def __init__(self, m, n):
        self.W = np.random.rand(m, n)  # m行n列を設定
        self.b = np.random.rand(m, 1)  # [] m行1列の要素をバイアスに与える
        
    def set_state(self, x):
        s = (self.W.dot(x))+1*self.b
        return s

    def activate(self, s):
        y = 1 / (1 + np.exp(-s))
        return y

    def output(self, x):
        return self.activate(self.set_state(x))

if __name__ == '__main__':
    n1 = Layer(2, 2) # 設定
    x1 = np.array([[1.],
                  [2.]])
    print("1層目：", n1.output(x1))
    
    n2 = Layer(2, 2)
    x2 = n1.output(x1)
    print("2層目：", n2.output(x2))
    
    n3 = Layer(2, 2)
    x3 = n1.output(x2)
    print("2層目：", n3.output(x3))
     

1層目： [[ 0.88349451]
 [ 0.90443479]]
2層目： [[ 0.83046119]
 [ 0.76666003]]
2層目： [[ 0.7506729 ]
 [ 0.71544728]]
